// eslint-disable-next-line no-undef
module.exports = {
    future: {
        removeDeprecatedGapUtilities: true,
        purgeLayersByDefault: true,
        defaultLineHeights: true,
        standardFontWeights: true,
    },
    purge: {
        enabled: false,
        content: ['./**/*.htm'],
    },
    theme: {
        extend: {},
        width: {
            auto: 'auto',
            '1/4': '25%',
            '1/3': '33.333333%',
            '1/2': '50%',
            '2/3': '66.666667%',
            '3/4': '75%',
            '4/4': '100%',
            full: '100%',
        },
        flex: (theme) => ({
            1: '1 1 0%',
            auto: '1 1 auto',
            initial: '0 1 auto',
            none: 'none',
            '1/4': '0 0 ' + theme('width.1/4'),
            '1/3': '0 0 ' + theme('width.1/3'),
            '1/2': '0 0 ' + theme('width.1/2'),
            '2/3': '0 0 ' + theme('width.2/4'),
            '3/4': '0 0 ' + theme('width.3/4'),
            '4/4': '0 0 ' + theme('width.4/4'),
        }),
        flexGrow: {
            0: '0',
            default: '1',
        },
        flexShrink: {
            0: '0',
            default: '1',
        },
        height: (theme) => ({
            auto: 'auto',
            ...theme('spacing'),
            full: '100%',
            screen: '100vh',
            '1/2': '10rem',
            '1/1': '20rem',
            '3/2': '30rem',
            '2/1': '40rem',
            16: '4rem',
            20: '5rem',
            24: '6rem',
            28: '7rem',
            32: '8rem',
            36: '9rem',
            40: '10rem',
            48: '12rem',
            56: '14rem',
            62: '16rem',
            72: '18rem',
            80: '20rem',
            header: '17.375rem',
        }),
    },
    variants: {},
    plugins: [],
};
