// eslint-disable-next-line no-undef
module.exports = {
    future: {
        removeDeprecatedGapUtilities: true,
        purgeLayersByDefault: true,
        defaultLineHeights: true,
        standardFontWeights: true,
    },
    purge: {
        content: ['./**/*.htm'],
    },
    theme: {
        extend: {},
        colors: {
            transparent: 'transparent',
            current: 'currentColor',

            black: '#000',
            white: '#fff',

            gray: {
                100: '#f7fafc',
                200: '#edf2f7',
                300: '#e2e8f0',
                400: '#cbd5e0',
                500: '#a0aec0',
                600: '#718096',
                700: '#4a5568',
                800: '#2d3748',
                900: '#1a202c',
            },
        },
        flex: (theme) => ({
            1: '1 1 0%',
            auto: '1 1 auto',
            initial: '0 1 auto',
            none: 'none',
            '1/4': '0 0 ' + theme('width.1/4'),
            '1/3': '0 0 ' + theme('width.1/3'),
            '1/2': '0 0 ' + theme('width.1/2'),
            '2/3': '0 0 ' + theme('width.2/4'),
            '3/4': '0 0 ' + theme('width.3/4'),
            '4/4': '0 0 ' + theme('width.4/4'),
        }),
        flexGrow: {
            0: '0',
            default: '1',
        },
        flexShrink: {
            0: '0',
            default: '1',
        },
        width: (theme) => ({
            auto: 'auto',
            ...theme('spacing'),
            '1/4': '25%',
            '1/3': '33.333333%',
            '1/2': '50%',
            '2/3': '66.666667%',
            '3/4': '75%',
            '4/4': '100%',
            full: '100%',
        }),
        height: (theme) => ({
            auto: 'auto',
            ...theme('spacing'),
            full: '100%',
            screen: '100vh',
            '1/2': '10rem',
            '1/1': '20rem',
            '3/2': '30rem',
            '2/1': '40rem',
            16: '4rem',
            20: '5rem',
            24: '6rem',
            28: '7rem',
            32: '8rem',
            36: '9rem',
            40: '10rem',
            48: '12rem',
            56: '14rem',
            62: '16rem',
            72: '18rem',
            80: '20rem',
            header: '17.375rem',
        }),
        maxHeight: {
            none: 'none',
            full: '100%',
            screen: '100vh',
        },
        maxWidth: (theme) => ({
            ...theme('maxHeight'),
        }),
        inset: (theme) => ({
            0: '0',
            ...theme('width'),
        }),
        spacing: {
            px: '1px',
            0: '0',
            1: '0.25rem',
            2: '0.5rem',
            3: '0.75rem',
            4: '1rem',
            5: '1.25rem',
            6: '1.5rem',
            8: '2rem',
            10: '2.5rem',
            12: '3rem',
            16: '4rem',
            20: '5rem',
            24: '6rem',
            32: '8rem',
            40: '10rem',
            48: '12rem',
            56: '14rem',
            64: '16rem',
        },
        translate: {
            '-full': '-100%',
            '-1/2': '-50%',
            '1/2': '50%',
            full: '100%',
        },
        fontSize: {
            xs: '0.75rem',
            sm: '0.875rem',
            base: '1rem',
            lg: '1.125rem',
            xl: '1.25rem',
            '2xl': '1.5rem',
            '3xl': '1.875rem',
            '4xl': '2.25rem',
            '5xl': '3rem',
            '6xl': '4rem',
            '7xl': '5rem',
        },
        fontWeight: {
            hairline: '100',
            thin: '200',
            light: '300',
            normal: '400',
            medium: '500',
            semibold: '600',
            bold: '700',
            extrabold: '800',
            black: '900',
        },
        margin: (theme, { negative }) => ({
            auto: 'auto',
            ...theme('spacing'),
            ...negative(theme('spacing')),
        }),
        padding: (theme) => ({
            ...theme('margin'),
        }),
        lineHeight: {
            none: '1',
            tight: '1.25',
            snug: '1.375',
            normal: '1.5',
            relaxed: '1.625',
            loose: '2',
            3: '.75rem',
            4: '1rem',
            5: '1.25rem',
            6: '1.5rem',
            7: '1.75rem',
            8: '2rem',
            9: '2.25rem',
            10: '2.5rem',
        },
        borderRadius: {
            none: '0',
            '1/2': '50%',
        },
        borderWidth: {
            default: '1px',
            0: '0',
            1: '1px',
            2: '2px',
            4: '4px',
            8: '8px',
        },
        opacity: {
            0: '0',
            25: '0.25',
            50: '0.5',
            75: '0.75',
            100: '1',
        },
        textColor: (theme) => theme('colors'),
        textOpacity: (theme) => theme('opacity'),
        backgroundOpacity: (theme) => theme('opacity'),
    },
    variants: {
        overflow: ['responsive'],
    },
    plugins: [],
};
