# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Block List

# Model Form Field configuration
form: $/xitara/voodooblocks/models/blocklist/fields.yaml

# Model Class name
modelClass: Xitara\VoodooBlocks\Models\Blocklist

# Default redirect location
defaultRedirect: xitara/voodooblocks/blocklists

# Create page
create:
    title: Create Block List
    redirect: xitara/voodooblocks/blocklists/update/:id
    redirectClose: xitara/voodooblocks/blocklists

# Update page
update:
    title: Edit Block List
    redirect: xitara/voodooblocks/blocklists
    redirectClose: xitara/voodooblocks/blocklists

# Preview page
preview:
    title: Preview Block List
