# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Text Pool

# Model Form Field configuration
form: $/xitara/dynamiccontent/models/text/fields.yaml

# Model Class name
modelClass: Xitara\DynamicContent\Models\Text

# Default redirect location
defaultRedirect: xitara/dynamiccontent/texts

# Create page
create:
    title: Create Text Pool
    redirect: xitara/dynamiccontent/texts/update/:id
    redirectClose: xitara/dynamiccontent/texts

# Update page
update:
    title: Edit Text Pool
    redirect: xitara/dynamiccontent/texts
    redirectClose: xitara/dynamiccontent/texts

# Preview page
preview:
    title: Preview Text Pool
